### ISSUE TITLE
Difference between average in app vs website tibber

### ISSUE THREAD

**Issue by mvdh02** [me-processware/TIbber#1]
Hello,

i'm very happy with you tool. Because the previous was nog working anymore. With this price information i control partly my home battery. I use the current price information en de average (day) price information.

And in this last part is the strange behaviour.  When i login in Tibber i see a average price of 31 cent/kwh (for 15-11-2024, Netherland).
In de domoticz integration i see a price of 29 cent/kwh for today (15-11-2024).

Today it's just 2 cent's. But the last wind-still days te difference was larger.

**Comment by me-processware** [comment]
Hey nice to see someone using it :) i would love to brainstorm a litte if you are interested in the tibber / charge / battery scripts i am creating. the problem you are facing is a timezone thing i think when programming in python (english) timezone's are always a problem. i will check if this is the case here also. i am using the script instead of the plugin so i can calculate the cheap hours from that data and push it to domoticz this script provides a average of 0,318 eur so that seems correct when i look at the app.

regards.

Henry

**Comment by mvdh02** [comment]
Hello Henry,  
thanks for the quick reply. Is it possible to change the plugin for this behaviour?? Or can i integrate the script in domoticz?

I'm always open for a brainstorm. A the moment i've got a growatt spa battery inverter. That i can control with some py.scripts. Domoticz controls the load in house. But the charing is done with node-red. To find the perfect (lowest) charge moments. A better solution would be great.

**Comment by me-processware** [comment]
yes i wil check and see if that's the problem the charge script i posted in my github does the most things this plugin can do except the realtime prices also it is not a dedicated domoticz plugin. the idea is simple i have a selection button for amount of hours i want to charge extra from 1 to 24 and if i select for example 5 hours it wil charge at the 5 cheapest hours of that day ( a little like grid rewards) you can find it here https://github.com/me-processware/tibberchargescript

**Comment by mvdh02** [comment]
I,ve seen you battery script before. At the moment I use node red with powersaver.no. I think this thous the same without the Domoticz integration. But I works wel with my battery. And you can select the amount of hours you want to charge. And if you want to combine the charge hours or not.

**Comment by me-processware** [comment]
> Hello,
> 
> i'm very happy with you tool. Because the previous was nog working anymore. With this price information i control partly my home battery. I use the current price information en de average (day) price information.
> 
> And in this last part is the strange behaviour. When i login in Tibber i see a average price of 31 cent/kwh (for 15-11-2024, Netherland). In de domoticz integration i see a price of 29 cent/kwh for today (15-11-2024).
> 
> Today it's just 2 cent's. But the last wind-still days te difference was larger.

it was a timezone issue default reports from tibber are utc 
So i created a timezone selection, and it is reporting correct now.
(be shure to update requirements.txt because of pytz dependency)

**Comment by mvdh02** [comment]
Thanks for the update / you're work. I will install the update and let you know if it works.
Thanks again.

**Comment by mvdh02** [comment]
Goodmorning. I've installed the new plugin on 2 systems. And the average price is now better in line with the app.
Thanks a lot.
